//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelDBKanalPROJE
{
    using System;
    using System.Collections.Generic;
    
    public partial class kanal
    {
        public kanal()
        {
            this.yayins = new HashSet<yayin>();
        }
    
        public int KanaIno { get; set; }
        public string kanaladi { get; set; }
        public int ciro { get; set; }
        public string adres { get; set; }
        public int reyting { get; set; }
        public int yayinId { get; set; }
    
        public virtual ICollection<yayin> yayins { get; set; }
    }
}
