//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelDBKanalPROJE
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1kanalContainer : DbContext
    {
        public Model1kanalContainer()
            : base("name=Model1kanalContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<kanal> kanalSet { get; set; }
        public DbSet<yayin> yayinSet { get; set; }
        public DbSet<sorumlu> sorumluSet { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
