//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelDBKanalPROJE
{
    using System;
    using System.Collections.Generic;
    
    public partial class sorumlu
    {
        public int sorumluno { get; set; }
        public string asoyad { get; set; }
        public string gorevi { get; set; }
        public int maas { get; set; }
        public int gorevsayisi { get; set; }
        public int yayinId { get; set; }
    
        public virtual yayin yayin { get; set; }
    }
}
