//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Araclar
    {
        public int AracNo { get; set; }
        public Nullable<int> AracFiyat { get; set; }
        public Nullable<int> AracAdet { get; set; }
        public string AracMarka { get; set; }
        public Nullable<int> AracModel { get; set; }
        public Nullable<int> AracYıl { get; set; }
        public string AracOzellik { get; set; }
        public string AracMotor { get; set; }
        public string AracPaket { get; set; }
        public string AracRenk { get; set; }
        public Nullable<int> SubeNo { get; set; }
    
        public virtual Subeler Subeler { get; set; }
    }
}
